### ISSUE TITLE
Island quest

### ISSUE THREAD

**Issue by Tomash667** [Tomash667/carpg#179]
ISLAND QUEST:
- [ ] 3d world map, roads, rivers, visible locations
- [ ] island
- [ ] swimming, diving
- [ ] ocean, rivers
- [ ] pregenerated world map, pregenerated locations
- [ ] traveling between locations
- [ ] cutscenes
- [ ] academy
- [ ] scripted quests
- [ ] boss battles
- [ ] womans
- [ ] better dungeons
- [ ] better outside locations
- [ ] shadows / lighting
- [ ] day & night cycle
- [ ] weather - rain
- [ ] calendar rework
- [ ] dark dungeons, carring torches
- [ ] new items: helmet, two handed weapons, throwable
- [ ] beach terrain
- [ ] dynamic loading
- [ ] combat system
- [ ] player fine/prison
- [ ] collectibles/achivements
- [ ] horse riding
- [ ] lots of new enemies/animations/models

Acts:
I - from start to discover zoe
II - to killing, reviving zoe
III - from II
IV - secret Rewritting history
